filebeat.prospectors:
- input_type: log
  paths:
    - logs/*.log
    - logs/*.txt
    -
filebeat.inputs:
- type: log
  paths:
    - /var/log/mysql/mysql-slow.log
  fields:
    log_type: mysql_slow_log

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]
