version: '2'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: myroslav
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --slow_query_log=1 --slow_query_log_file=/var/log/mysql/mysql-slow.log --long_query_time=1
    networks:
      - sql-elk-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  elk:
    container_name: elk
    image: tuongvx/docker-elk-filebeat:8.10.4
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ./logstash:/etc/logstash/conf.d
      - ./elasticsearch:/usr/share/elasticsearch/data
      - ./kibana:/opt/kibana/config/
      - ./filebeat:/etc/filebeat
    depends_on:
      - mysql
    networks:
      - sql-elk-network

volumes:
  logstash:
  filebeat:
#  elasticsearch:
  kibana:
  mysql:

networks:
  sql-elk-network:
    driver: bridge